table 'Movies to Watch Directors'
	lineageTag: 07455fb2-f751-465a-a98d-7a786c9289d9

	column Movie
		dataType: string
		lineageTag: 7db37c8c-7cab-425b-ad73-48146d99cb29
		summarizeBy: none
		sourceColumn: Movie

		annotation SummarizationSetBy = Automatic

	column IMDb
		dataType: double
		lineageTag: 8a062bb2-c060-4080-a922-e50156673c2d
		summarizeBy: none
		sourceColumn: IMDb

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: c57179c6-643a-472d-bc89-1f25dc2b6171
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Genre1
		dataType: string
		lineageTag: d1fec03f-ae8d-4a5c-9d72-1ff07d8bedd2
		summarizeBy: none
		sourceColumn: Genre1

		annotation SummarizationSetBy = Automatic

	column Genre2
		dataType: string
		lineageTag: 6433b29e-d46d-41b3-a7df-f5e4a62438eb
		summarizeBy: none
		sourceColumn: Genre2

		annotation SummarizationSetBy = Automatic

	column Genre3
		dataType: string
		lineageTag: d0049e1b-be9e-4591-8ebf-e64d02a79393
		summarizeBy: none
		sourceColumn: Genre3

		annotation SummarizationSetBy = Automatic

	column Director
		dataType: string
		lineageTag: 1a1d13c0-ee3f-4669-9503-9b7a585e6c49
		summarizeBy: none
		sourceColumn: Director
		sortByColumn: 'Director Sort Score'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column RT
		dataType: double
		formatString: 0
		lineageTag: e1998d1a-db26-43a5-a572-3e0928969619
		summarizeBy: none
		sourceColumn: RT

		annotation SummarizationSetBy = Automatic

	column Actor
		dataType: string
		lineageTag: 881257a1-af25-44f5-b041-e1edfed5ce0e
		summarizeBy: none
		sourceColumn: Actor

		annotation SummarizationSetBy = Automatic

	column 'Actor 2'
		dataType: string
		lineageTag: d15d994b-b26f-4c98-9b49-d56c7f86eca6
		summarizeBy: none
		sourceColumn: Actor 2

		annotation SummarizationSetBy = Automatic

	column 'Actor 3'
		dataType: string
		lineageTag: 50357a63-8199-42c6-8a69-09267456426e
		summarizeBy: none
		sourceColumn: Actor 3

		annotation SummarizationSetBy = Automatic

	column 'Predicted Score'
		dataType: double
		lineageTag: 656df45e-d8a6-4f7b-8f94-6a2a25a696fa
		summarizeBy: none
		sourceColumn: Predicted Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Runtime
		dataType: int64
		formatString: 0
		lineageTag: 5750af5a-003b-4e4c-bf51-87f4350b1101
		summarizeBy: none
		sourceColumn: Runtime

		annotation SummarizationSetBy = Automatic

	column Metascore
		dataType: double
		lineageTag: 6f35c694-f2b7-4b22-a49b-b3e08f20ab85
		summarizeBy: none
		sourceColumn: Metascore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rated
		dataType: string
		lineageTag: 2832e1d3-2a19-48c2-af8e-6ff05dd7908a
		summarizeBy: none
		sourceColumn: Rated

		annotation SummarizationSetBy = Automatic

	column Oscar_Wins
		dataType: int64
		formatString: 0
		lineageTag: 6fc21d5b-677c-4c50-a511-0c8ea835921c
		summarizeBy: none
		sourceColumn: Oscar_Wins

		annotation SummarizationSetBy = Automatic

	column Total_Wins
		dataType: int64
		formatString: 0
		lineageTag: 35c09694-1858-4d5f-9d46-93798691e14d
		summarizeBy: none
		sourceColumn: Total_Wins

		annotation SummarizationSetBy = Automatic

	column Keywords
		dataType: string
		lineageTag: 829ac9ea-8130-4bd0-9078-3d7dfabb3691
		summarizeBy: none
		sourceColumn: Keywords

		annotation SummarizationSetBy = Automatic

	column Raw_Predicted
		dataType: double
		lineageTag: 328ff30d-85b8-4e6a-a22a-1f469beb6f11
		summarizeBy: none
		sourceColumn: Raw_Predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Director Sort Score'
		dataType: string
		lineageTag: 4f649c21-f38e-4866-9c33-ecebd894ca22
		summarizeBy: none
		sourceColumn: Director Sort Score

		annotation SummarizationSetBy = Automatic

	column 'Star Percentage'
		dataType: string
		lineageTag: 445fa73e-4aed-4d5a-8c52-7024a2e0f84f
		summarizeBy: none
		sourceColumn: Star Percentage

		annotation SummarizationSetBy = Automatic

	column Star
		dataType: string
		lineageTag: b377c84a-2210-4b90-9b65-e693c37fec2d
		summarizeBy: none
		sourceColumn: Star

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: string
		lineageTag: 773342fd-b373-4453-b8f2-c128895b6e7b
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	partition 'Movies to Watch Directors' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/TylerGrossi/Movie-Rankings/refs/heads/main/data/processed/Predicted_Scores.csv"),[Delimiter=",", Columns=22, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers1" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Movie", type text}, {"Predicted Score", type number}, {"Year", Int64.Type}, {"Runtime", Int64.Type}, {"Actor", type text}, {"Actor 2", type text}, {"Actor 3", type text}, {"Director", type text}, {"Genre1", type text}, {"Genre2", type text}, {"Genre3", type text}, {"IMDb", type number}, {"RT", type number}, {"Raw_Predicted", type number}, {"Total_Wins", Int64.Type}, {"Oscar_Wins", Int64.Type}, {"Metascore", type number}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type1", {"Movie"}),
				    // New steps below
				    ExcelSource = Excel.Workbook(File.Contents("C:\Users\Owner\Desktop\Tyler\OneDrive\Projects\Movies\Movies Ranks.xlsm"), null, true),
				    DirectorRankings = ExcelSource{[Item="Director Rankings",Kind="Sheet"]}[Data],
				    #"DR Promoted Headers" = Table.PromoteHeaders(DirectorRankings, [PromoteAllScalars=true]),
				    #"DR Selected Columns" = Table.SelectColumns(#"DR Promoted Headers", {"Director", "Rating"}),
				    #"Merged" = Table.NestedJoin(#"Removed Duplicates", "Director", #"DR Selected Columns", "Director", "DirectorRankings", JoinKind.LeftOuter),
				    #"Expanded" = Table.ExpandTableColumn(#"Merged", "DirectorRankings", {"Rating"}, {"Director Sort Score"})
				in
				    #"Expanded"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

