table 'Director Rankings'
	lineageTag: 2f07cbf8-597a-476f-8a90-3c06120b80b0

	measure 'Top Movie for Director' =
			
			VAR CurrentDirector = MAX('Director Rankings'[Director])
			RETURN
			CALCULATE(
			    MAX('Movie_Directors'[Movie]),
			    FILTER(
			        ALL('Movie_Directors'),
			        'Movie_Directors'[Director] = CurrentDirector &&
			        RANKX(
			            FILTER(ALL('Movie_Directors'), 'Movie_Directors'[Director] = CurrentDirector),
			            'Movie_Directors'[All],
			            ,
			            DESC,
			            DENSE
			        ) = 1
			    )
			)
		lineageTag: 85db543c-b1e5-4af0-9cfd-c083be080cba

	measure 'Top Movie 2 for Director' =
			
			VAR CurrentDirector = MAX('Director Rankings'[Director])
			RETURN
			CALCULATE(
			    MAX('Movie_Directors'[Movie]),
			    FILTER(
			        ALL('Movie_Directors'),
			        'Movie_Directors'[Director] = CurrentDirector &&
			        RANKX(
			            FILTER(ALL('Movie_Directors'), 'Movie_Directors'[Director] = CurrentDirector),
			            'Movie_Directors'[All] + (1 / UNICODE('Movie_Directors'[Movie])), -- Tie breaker logic
			            ,
			            DESC,
			            DENSE
			        ) = 2
			    )
			)
		lineageTag: 29fb2fb3-82c9-44a3-95e6-9661f6914f29

	measure 'Top Movie 3 for Director' =
			
			VAR CurrentDirector = MAX('Director Rankings'[Director])
			RETURN
			CALCULATE(
			    MAX('Movie_Directors'[Movie]),
			    FILTER(
			        ALL('Movie_Directors'),
			        'Movie_Directors'[Director] = CurrentDirector &&
			        RANKX(
			            FILTER(ALL('Movie_Directors'), 'Movie_Directors'[Director] = CurrentDirector),
			            'Movie_Directors'[All] + (UNICODE(LEFT('Movie_Directors'[Movie], 1)) / 100000),
			            ,
			            DESC,
			            DENSE
			        ) = 3
			    )
			)
		lineageTag: 28aaef17-7cee-4db8-a942-08891c8d68a1

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: 33235e8e-81fd-499e-b182-a51897e2b5dd
		summarizeBy: none
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	column Score
		dataType: double
		formatString: 0.0
		lineageTag: d3f54af4-a4c8-4821-b874-525504532742
		summarizeBy: sum
		sourceColumn: Score

		annotation SummarizationSetBy = Automatic

	column Movies
		dataType: int64
		formatString: 0
		lineageTag: 86cb9dc8-fa62-4909-9830-7fb10d9e77bb
		summarizeBy: sum
		sourceColumn: Movies

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: double
		formatString: 0.0
		lineageTag: adba1a2b-4804-4c31-afac-141637e33960
		summarizeBy: sum
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	column Director
		dataType: string
		lineageTag: 0fe89e9d-7e75-461d-8536-4f389a5419aa
		summarizeBy: none
		sourceColumn: Director
		sortByColumn: Rating

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Average
		dataType: double
		formatString: 0.0
		lineageTag: 1dde6410-aee8-4812-9545-af890a01a7e8
		summarizeBy: sum
		sourceColumn: Average

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition 'Director Rankings' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Owner\Desktop\Tyler\OneDrive\Projects\Movies\Movies Ranks.xlsm"), null, true),
				    #"Director Rankings_Sheet" = Source{[Item="Director Rankings",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Director Rankings_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"#", Int64.Type}, {"Director", type text}, {"Score", type number}, {"Movies", Int64.Type}, {"Rating", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"#", "Rank"}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Renamed Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

