table Movie_WatchedWith
	lineageTag: e8f2a3b1-c4d5-4e6f-7a8b-9c0d1e2f3a4b

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: f9e0b2c3-d4e5-4f6a-7b8c-9d0e1f2a3b4c
		summarizeBy: sum
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	column Movie
		dataType: string
		lineageTag: a0b1c2d3-e4f5-4a6b-7c8d-9e0f1a2b3c4d
		summarizeBy: none
		sourceColumn: Movie

		annotation SummarizationSetBy = Automatic

	column Score
		dataType: double
		lineageTag: b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e
		summarizeBy: sum
		sourceColumn: Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: c2d3e4f5-a6b7-4c8d-9e0f-1a2b3c4d5e6f
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Watch Location'
		dataType: string
		lineageTag: d3e4f5a6-b7c8-4d9e-0f1a-2b3c4d5e6f7a
		summarizeBy: none
		sourceColumn: Watch Location

		annotation SummarizationSetBy = Automatic

	column 'Watched With'
		dataType: string
		lineageTag: e4f5a6b7-c8d9-4e0f-1a2b-3c4d5e6f7a8b
		summarizeBy: none
		sourceColumn: Watched With

		annotation SummarizationSetBy = Automatic

	column Director
		dataType: string
		lineageTag: f5a6b7c8-d9e0-4f1a-2b3c-4d5e6f7a8b9c
		summarizeBy: none
		sourceColumn: Director

		annotation SummarizationSetBy = Automatic

	partition Movie_WatchedWith = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Owner\Desktop\Tyler\OneDrive\Projects\Movies\Movies Ranks.xlsm"), null, true),
				    #"Movie Rankings_Sheet" = Source{[Item="Movie Rankings",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Movie Rankings_Sheet", [PromoteAllScalars=true]),
				    #"Removed Blank Rows" = Table.SelectRows(#"Promoted Headers", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Blank Rows",{"Year_1", "(Multiple Items)"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Rank", Int64.Type}, {"Movie", type any}, {"Score", type number}, {"Year", Int64.Type}}),
				    #"Selected Columns" = Table.SelectColumns(#"Changed Type", {"Rank", "Movie", "Score", "Year", "Watch Location", "Watched With", "Director"}),
				    #"Removed Nulls" = Table.SelectRows(#"Selected Columns", each [Watched With] <> null and [Watched With] <> ""),
				    #"Split Column" = Table.TransformColumns(
				        #"Removed Nulls",
				        {{"Watched With", each
				            let
				                normalized = Text.Replace(_, " and ", ", "),
				                parts = List.Transform(Text.Split(normalized, ", "), Text.Trim)
				            in
				                List.Select(parts, each _ <> null and _ <> ""),
				            type list}}
				    ),
				    #"Expanded Column" = Table.ExpandListColumn(#"Split Column", "Watched With"),
				    #"Removed Empty" = Table.SelectRows(#"Expanded Column", each [Watched With] <> null and [Watched With] <> "")
				in
				    #"Removed Empty"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
